"""add nodes and edges to workflows

Revision ID: 640f2eb37426
Revises: cc328a90d01c
Create Date: 2026-03-06 04:19:29.105453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640f2eb37426'
down_revision = 'cc328a90d01c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nodes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('edges', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('edges')
        batch_op.drop_column('nodes')

    # ### end Alembic commands ###
